const products = [
  {
    name: 'Classic Fit T-Shirt',
    slug: 'classic-fit-tshirt',
    tagline: 'Your canvas, your story',
    description: 'Premium 100% combed ring-spun cotton t-shirt. Pre-shrunk fabric ensures lasting fit. Perfect for custom designs with our state-of-the-art DTG printing. Features a seamless collar, double-needle stitching, and a tear-away label for tag-free comfort.',
    category: 't-shirts',
    basePrice: 29.99,
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800', 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800'],
    colors: [{ name: 'Black', hex: '#000000' }, { name: 'White', hex: '#FFFFFF' }, { name: 'Navy', hex: '#1B2838' }, { name: 'Heather Grey', hex: '#B0B0B0' }, { name: 'Forest Green', hex: '#228B22' }, { name: 'Burgundy', hex: '#800020' }],
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    variants: [
      { size: 'S', color: 'Black', colorHex: '#000000', price: 29.99, stock: 100 },
      { size: 'M', color: 'Black', colorHex: '#000000', price: 29.99, stock: 100 },
      { size: 'L', color: 'Black', colorHex: '#000000', price: 29.99, stock: 100 },
      { size: 'XL', color: 'Black', colorHex: '#000000', price: 31.99, stock: 100 },
      { size: 'S', color: 'White', colorHex: '#FFFFFF', price: 29.99, stock: 100 },
      { size: 'M', color: 'White', colorHex: '#FFFFFF', price: 29.99, stock: 100 },
      { size: 'L', color: 'White', colorHex: '#FFFFFF', price: 29.99, stock: 100 },
      { size: 'XL', color: 'White', colorHex: '#FFFFFF', price: 31.99, stock: 100 },
      { size: 'S', color: 'Navy', colorHex: '#1B2838', price: 29.99, stock: 100 },
      { size: 'M', color: 'Navy', colorHex: '#1B2838', price: 29.99, stock: 100 },
      { size: 'L', color: 'Navy', colorHex: '#1B2838', price: 29.99, stock: 100 },
      { size: 'XL', color: 'Navy', colorHex: '#1B2838', price: 31.99, stock: 100 },
    ],
    tags: ['cotton', 'classic', 'essential', 'everyday'],
    features: ['100% Combed Ring-Spun Cotton', 'Pre-shrunk Fabric', 'Seamless Collar', 'Double-Needle Stitching', 'Tear-Away Label', 'DTG Printable'],
    featured: true,
    bestseller: true,
    rating: 4.8,
    reviewCount: 256,
  },
  {
    name: 'Premium Hoodie',
    slug: 'premium-hoodie',
    tagline: 'Warmth meets expression',
    description: 'Ultra-soft 80/20 cotton-polyester blend hoodie with a brushed fleece interior. Features a kangaroo pocket, adjustable drawstring hood, and ribbed cuffs. Our premium blank for custom designs that demand attention.',
    category: 'hoodies',
    basePrice: 54.99,
    images: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800', 'https://images.unsplash.com/photo-1578768079052-aa76e52ff62e?w=800', 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800'],
    colors: [{ name: 'Black', hex: '#000000' }, { name: 'Grey', hex: '#808080' }, { name: 'Navy', hex: '#1B2838' }, { name: 'Maroon', hex: '#800020' }],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    variants: [
      { size: 'M', color: 'Black', colorHex: '#000000', price: 54.99, stock: 80 },
      { size: 'L', color: 'Black', colorHex: '#000000', price: 54.99, stock: 80 },
      { size: 'XL', color: 'Black', colorHex: '#000000', price: 57.99, stock: 80 },
      { size: 'M', color: 'Grey', colorHex: '#808080', price: 54.99, stock: 80 },
      { size: 'L', color: 'Grey', colorHex: '#808080', price: 54.99, stock: 80 },
      { size: 'XL', color: 'Grey', colorHex: '#808080', price: 57.99, stock: 80 },
    ],
    tags: ['fleece', 'warm', 'cotton-blend', 'premium'],
    features: ['80/20 Cotton-Polyester Blend', 'Brushed Fleece Interior', 'Kangaroo Pocket', 'Adjustable Drawstring Hood', 'Ribbed Cuffs & Hem', 'DTG Printable'],
    featured: true,
    bestseller: true,
    rating: 4.9,
    reviewCount: 189,
  },
  {
    name: 'Structured Cap',
    slug: 'structured-cap',
    tagline: 'Top off your look',
    description: 'High-profile structured cap with a flat brim. Made from 100% cotton with a pre-curved visor. Features an adjustable snapback closure for a perfect fit. The ideal canvas for embroidered or printed designs.',
    category: 'caps',
    basePrice: 24.99,
    images: ['https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800', 'https://images.unsplash.com/photo-1620327467532-6ebaca6273ed?w=800'],
    colors: [{ name: 'Black', hex: '#000000' }, { name: 'Navy', hex: '#1B2838' }, { name: 'Olive', hex: '#556B2F' }, { name: 'White', hex: '#FFFFFF' }],
    sizes: ['One Size'],
    variants: [
      { size: 'One Size', color: 'Black', colorHex: '#000000', price: 24.99, stock: 150 },
      { size: 'One Size', color: 'Navy', colorHex: '#1B2838', price: 24.99, stock: 150 },
      { size: 'One Size', color: 'Olive', colorHex: '#556B2F', price: 24.99, stock: 150 },
      { size: 'One Size', color: 'White', colorHex: '#FFFFFF', price: 24.99, stock: 150 },
    ],
    tags: ['snapback', 'cotton', 'structured', 'adjustable'],
    features: ['100% Cotton', 'High-Profile Structure', 'Flat Brim', 'Snapback Closure', 'Pre-Curved Visor', 'Embroidery Ready'],
    featured: true,
    bestseller: false,
    rating: 4.6,
    reviewCount: 98,
  },
  {
    name: 'Canvas Wall Art',
    slug: 'canvas-wall-art',
    tagline: 'Make your walls talk',
    description: 'Gallery-quality stretched canvas print. Made from acid-free, archival-quality cotton canvas with a matte finish. Gallery-wrapped on a solid wood frame with mirrored edges. Ready to hang with pre-installed hardware.',
    category: 'wall-art',
    basePrice: 39.99,
    images: ['https://images.unsplash.com/photo-1513519245088-0e12902e35ca?w=800', 'https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=800'],
    colors: [{ name: 'Standard', hex: '#F5F5DC' }],
    sizes: ['8x10"', '11x14"', '16x20"', '18x24"', '24x36"'],
    variants: [
      { size: '8x10"', color: 'Standard', colorHex: '#F5F5DC', price: 29.99, stock: 50 },
      { size: '11x14"', color: 'Standard', colorHex: '#F5F5DC', price: 39.99, stock: 50 },
      { size: '16x20"', color: 'Standard', colorHex: '#F5F5DC', price: 54.99, stock: 50 },
      { size: '24x36"', color: 'Standard', colorHex: '#F5F5DC', price: 79.99, stock: 50 },
    ],
    tags: ['canvas', 'wall-decor', 'art-print', 'gallery'],
    features: ['Archival-Quality Canvas', 'Matte Finish', 'Solid Wood Frame', 'Mirrored Edges', 'Ready to Hang', 'Acid-Free'],
    featured: true,
    bestseller: false,
    rating: 4.7,
    reviewCount: 134,
  },
  {
    name: 'Ceramic Mug',
    slug: 'ceramic-mug',
    tagline: 'Sip in style',
    description: 'Premium 11oz ceramic mug with a glossy finish. Full-color sublimation printing that won\'t fade or peel. Microwave and dishwasher safe. The perfect canvas for your favorite designs, inside and out.',
    category: 'mugs',
    basePrice: 14.99,
    images: ['https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=800', 'https://images.unsplash.com/photo-1577937927133-66ef06acdf18?w=800'],
    colors: [{ name: 'White', hex: '#FFFFFF' }, { name: 'Black', hex: '#000000' }],
    sizes: ['11oz', '15oz'],
    variants: [
      { size: '11oz', color: 'White', colorHex: '#FFFFFF', price: 14.99, stock: 200 },
      { size: '15oz', color: 'White', colorHex: '#FFFFFF', price: 17.99, stock: 200 },
    ],
    tags: ['ceramic', 'dishwasher-safe', 'microwave-safe', 'sublimation'],
    features: ['Premium Ceramic', 'Glossy Finish', '11oz Capacity', 'Dishwasher Safe', 'Microwave Safe', 'Full-Color Sublimation'],
    featured: false,
    bestseller: true,
    rating: 4.5,
    reviewCount: 312,
  },
  {
    name: 'Tough Phone Case',
    slug: 'tough-phone-case',
    tagline: 'Protect what matters',
    description: 'Impact-resistant polycarbonate phone case with a soft-touch finish. Dual-layer protection with a shock-absorbing inner core and hard outer shell. Precise cutouts for ports and buttons. Custom printed with vibrant UV-resistant inks.',
    category: 'phone-cases',
    basePrice: 19.99,
    images: ['https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=800', 'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=800'],
    colors: [{ name: 'Clear', hex: '#F0F0F0' }, { name: 'Black', hex: '#000000' }],
    sizes: ['iPhone 15 Pro', 'iPhone 15 Pro Max', 'iPhone 16 Pro', 'iPhone 16 Pro Max', 'Samsung S25', 'Samsung S25 Ultra'],
    variants: [
      { size: 'iPhone 16 Pro', color: 'Clear', colorHex: '#F0F0F0', price: 19.99, stock: 100 },
      { size: 'iPhone 16 Pro Max', color: 'Clear', colorHex: '#F0F0F0', price: 21.99, stock: 100 },
      { size: 'iPhone 16 Pro', color: 'Black', colorHex: '#000000', price: 19.99, stock: 100 },
      { size: 'iPhone 16 Pro Max', color: 'Black', colorHex: '#000000', price: 21.99, stock: 100 },
    ],
    tags: ['phone-case', 'protective', 'impact-resistant', 'slim'],
    features: ['Dual-Layer Protection', 'Shock-Absorbing Core', 'Soft-Touch Finish', 'Precise Cutouts', 'UV-Resistant Inks', 'Wireless Charging Compatible'],
    featured: false,
    bestseller: false,
    rating: 4.4,
    reviewCount: 78,
  },
  {
    name: 'Tote Bag',
    slug: 'tote-bag',
    tagline: 'Carry your world',
    description: 'Heavy-duty 100% cotton canvas tote bag with extra-long reinforced handles. Generous 15" x 16" size fits all your essentials. Natural, eco-friendly fabric that takes prints beautifully.',
    category: 'bags',
    basePrice: 22.99,
    images: ['https://images.unsplash.com/photo-1597484661643-2f5fef640dd1?w=800', 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=800'],
    colors: [{ name: 'Natural', hex: '#D2B48C' }, { name: 'Black', hex: '#000000' }],
    sizes: ['Standard', 'Large'],
    variants: [
      { size: 'Standard', color: 'Natural', colorHex: '#D2B48C', price: 22.99, stock: 120 },
      { size: 'Large', color: 'Natural', colorHex: '#D2B48C', price: 27.99, stock: 120 },
    ],
    tags: ['canvas', 'eco-friendly', 'reusable', 'cotton'],
    features: ['100% Cotton Canvas', 'Reinforced Handles', '15" x 16" Size', 'Eco-Friendly', 'Machine Washable', 'Custom Printable'],
    featured: false,
    bestseller: true,
    rating: 4.7,
    reviewCount: 145,
  },
  {
    name: 'Premium Poster Print',
    slug: 'premium-poster-print',
    tagline: 'Big impressions',
    description: 'Museum-quality poster print on 200gsm archival matte paper. Vibrant, fade-resistant colors with a smooth matte finish. Printed with archival pigment inks for longevity. Perfect for framing or pinning.',
    category: 'posters',
    basePrice: 18.99,
    images: ['https://images.unsplash.com/photo-1564934422807-3a2df1a4afa5?w=800', 'https://images.unsplash.com/photo-1580130371944-1e0c0cfc038e?w=800'],
    colors: [{ name: 'Matte', hex: '#F0F0F0' }],
    sizes: ['11x17"', '18x24"', '24x36"'],
    variants: [
      { size: '11x17"', color: 'Matte', colorHex: '#F0F0F0', price: 18.99, stock: 200 },
      { size: '18x24"', color: 'Matte', colorHex: '#F0F0F0', price: 29.99, stock: 200 },
      { size: '24x36"', color: 'Matte', colorHex: '#F0F0F0', price: 39.99, stock: 200 },
    ],
    tags: ['poster', 'art-print', 'matte', 'archival'],
    features: ['200gsm Archival Paper', 'Matte Finish', 'Fade-Resistant', 'Pigment Inks', 'Museum Quality', 'Made to Order'],
    featured: false,
    bestseller: false,
    rating: 4.6,
    reviewCount: 67,
  },
  {
    name: 'Performance Tee',
    slug: 'performance-tee',
    tagline: 'Train in expression',
    description: 'Moisture-wicking 100% polyester performance t-shirt. Quick-dry fabric with anti-microbial properties. Flatlock seams prevent chafing. Reflective details for visibility. Your designs, now in activewear.',
    category: 't-shirts',
    basePrice: 34.99,
    images: ['https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800', 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800'],
    colors: [{ name: 'Black', hex: '#000000' }, { name: 'Royal Blue', hex: '#4169E1' }, { name: 'Charcoal', hex: '#36454F' }],
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    variants: [
      { size: 'M', color: 'Black', colorHex: '#000000', price: 34.99, stock: 80 },
      { size: 'L', color: 'Black', colorHex: '#000000', price: 34.99, stock: 80 },
      { size: 'XL', color: 'Black', colorHex: '#000000', price: 36.99, stock: 80 },
      { size: 'M', color: 'Royal Blue', colorHex: '#4169E1', price: 34.99, stock: 80 },
      { size: 'L', color: 'Royal Blue', colorHex: '#4169E1', price: 34.99, stock: 80 },
    ],
    tags: ['performance', 'activewear', 'moisture-wicking', 'polyester'],
    features: ['Moisture-Wicking', 'Quick-Dry', 'Anti-Microbial', 'Flatlock Seams', 'Reflective Details', 'Sublimation Ready'],
    featured: false,
    bestseller: false,
    rating: 4.3,
    reviewCount: 56,
  },
  {
    name: 'Heavyweight Hoodie',
    slug: 'heavyweight-hoodie',
    tagline: 'Built for the cold',
    description: 'Ultra-heavy 400GSM hoodie made from 100% organic cotton. Double-lined hood with a thick fleece interior. YKK zipper, ribbed side panels, and a hidden pocket. The ultimate premium blank for statement designs.',
    category: 'hoodies',
    basePrice: 79.99,
    images: ['https://images.unsplash.com/photo-1597045566677-8cf032ed8434?w=800', 'https://images.unsplash.com/photo-1578768079052-aa76e52ff62e?w=800'],
    colors: [{ name: 'Black', hex: '#000000' }, { name: 'Cream', hex: '#FFFDD0' }, { name: 'Olive', hex: '#556B2F' }],
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    variants: [
      { size: 'L', color: 'Black', colorHex: '#000000', price: 79.99, stock: 40 },
      { size: 'XL', color: 'Black', colorHex: '#000000', price: 82.99, stock: 40 },
      { size: 'L', color: 'Cream', colorHex: '#FFFDD0', price: 79.99, stock: 40 },
      { size: 'XL', color: 'Cream', colorHex: '#FFFDD0', price: 82.99, stock: 40 },
    ],
    tags: ['heavyweight', 'organic-cotton', 'premium', 'winter'],
    features: ['400GSM Heavyweight', '100% Organic Cotton', 'Double-Lined Hood', 'YKK Zipper', 'Ribbed Side Panels', 'Hidden Pocket'],
    featured: true,
    bestseller: false,
    rating: 4.9,
    reviewCount: 43,
  },
];

module.exports = { products };
